name: thwstoken
description: "THWS Utility Token App – Frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WalletConnect (stable)
  walletconnect_flutter_v2: ^2.0.14

  # Web3 / Blockchain interaction
  web3dart: ^2.7.3
  http: ^1.1.0

  # QR Code (for WalletConnect pairing, if needed)
  qr_flutter: ^4.1.0

  # Permissions (camera for QR scan, etc.)
  permission_handler: ^11.3.1

  # External links (open MetaMask, browser, etc.)
  url_launcher: ^6.2.0
  mobile_scanner: ^6.0.2
  shared_preferences: ^2.3.2

  # iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/thws_logo_english.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true


  assets:
    # icons
    - assets/icons/

    # contract ABIs
    - assets/abi/
