spring.application.name=thws-coin-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/thws_coin
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

blockchain.enabled=false


#Hardhat private key?i kullanabilirsin.
#blockchain.private-key=0xABC123...  # test key

# Hardhat deploy etti?inde olu?an kontrat adresini buraya yazacaks?n:
# blockchain.payment-manager-address=0xYourContractAddress

